language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dntcryplz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dntcryplz/docker-react npm run test